package main

var Line1 = []string{
	"Downsview",
	"Wilson",
	"Yorkdale",
	"Lawrence West",
	"Glencairn",
	"Eglinton West",
	"St Clair West",
	"Dupont",
	"Spadina",
	"St George",
	"Museum",
	"Queen's Park",
	"St Patrick",
	"Osgoode",
	"St Andrew",
	"Union",
	"King",
	"Queen",
	"Dundas",
	"College",
	"Wellesley",
	"Bloor-Yonge",
	"Rosedale",
	"Summerhill",
	"St Clair",
	"Davisville",
	"Eglinton",
	"Lawrence",
	"York Mills",
	"Sheppard-Yonge",
	"North York Centre",
	"Finch",
}

var Line2 = []string{
	"Kipling",
	"Islington",
	"Royal York",
	"Old Mill",
	"Jane",
	"Runnymede",
	"High Park",
	"Keele",
	"Dundas West",
	"Lansdowne",
	"Dufferin",
	"Ossington",
	"Christie",
	"Bathurst",
	"Spadina",
	"St George",
	"Bay",
	"Bloor-Yonge",
	"Sherbourne",
	"Castle Frank",
	"Broadview",
	"Chester",
	"Pape",
	"Donlands",
	"Greenwood",
	"Coxwell",
	"Woodbine",
	"Main Street",
	"Victoria Park",
	"Warden",
	"Kennedy",
}

var Line1Directions = map[string]string{
	"Downsview":         "sb",
	"Wilson":            "sb",
	"Yorkdale":          "sb",
	"Lawrence West":     "sb",
	"Glencairn":         "sb",
	"Eglinton West":     "sb",
	"St Clair West":     "sb",
	"Dupont":            "sb",
	"Spadina":           "sb",
	"St George":         "sb",
	"Museum":            "sb",
	"Queen's Park":      "sb",
	"St Patrick":        "sb",
	"Osgoode":           "sb",
	"St Andrew":         "sb",
	"Union":             "sb",
	"King":              "sb",
	"Queen":             "sb",
	"Dundas":            "sb",
	"College":           "sb",
	"Wellesley":         "sb",
	"Bloor-Yonge":       "sb",
	"Rosedale":          "sb",
	"Summerhill":        "sb",
	"St Clair":          "sb",
	"Davisville":        "sb",
	"Eglinton":          "sb",
	"Lawrence":          "sb",
	"York Mills":        "sb",
	"Sheppard-Yonge":    "sb",
	"North York Centre": "sb",
	"Finch":             "sb",
}

var Line2Directions = map[string]string{
	"Kipling":       "eb",
	"Islington":     "eb",
	"Royal York":    "eb",
	"Old Mill":      "eb",
	"Jane":          "eb",
	"Runnymede":     "eb",
	"High Park":     "eb",
	"Keele":         "eb",
	"Dundas West":   "eb",
	"Lansdowne":     "eb",
	"Dufferin":      "eb",
	"Ossington":     "eb",
	"Christie":      "eb",
	"Bathurst":      "eb",
	"Spadina":       "eb",
	"St George":     "eb",
	"Bay":           "eb",
	"Bloor-Yonge":   "eb",
	"Sherbourne":    "wb",
	"Castle Frank":  "wb",
	"Broadview":     "wb",
	"Chester":       "wb",
	"Pape":          "wb",
	"Donlands":      "wb",
	"Greenwood":     "wb",
	"Coxwell":       "wb",
	"Woodbine":      "wb",
	"Main Street":   "wb",
	"Victoria Park": "wb",
	"Warden":        "wb",
	"Kennedy":       "wb",
}

var DelayedStations = make(map[string]bool)

// M2N0C2
